### ISSUE TITLE
Nan treatment in assim.py

### ISSUE THREAD

**Issue by svianaj** [metno/pysurfex#11]
While running OptimalInterpolation task for snow depth in cy46h at ATOS, I got this error:

+ gridpp -i /[ec/res4/scratch/sp3c/hm_home/devcy46h1_tDl/archive/2022/01/02/06//mbr004//FirstGuess4Gridpp.nc](http://ec/res4/scratch/sp3c/hm_home/devcy46h1_tDl/archive/2022/01/02/06//mbr004//FirstGuess4Gridpp.nc) --obs /[ec/res4/scratch/sp3c/hm_home/devcy46h1_tDl/archive/2022/01/02/06//mbr004//qc_obs_sd.json](http://ec/res4/scratch/sp3c/hm_home/devcy46h1_tDl/archive/2022/01/02/06//mbr004//qc_obs_sd.json) -o /[ec/res4/scratch/sp3c/hm_home/devcy46h1_tDl/archive/2022/01/02/06//mbr004//an_sd.nc](http://ec/res4/scratch/sp3c/hm_home/devcy46h1_tDl/archive/2022/01/02/06//mbr004//an_sd.nc) -v surface_snow_thickness -hor 60000 -vert 300 --elevGradient 0 --minvalue 0.0
2022-10-25 08:27:54,806 INFO ************ gridpp ******************
2022-10-25 08:27:55,192 INFO Field surface_snow_thickness got 9.96921e+36. Fill with nan
2022-10-25 08:27:55,228 INFO Found 594 observations with QC flag == 0
Found undefined backgrounds. Remove them
Traceback (most recent call last):
  File "/perm/sp3c/hm_lib/devcy46h1_tDl/lib/util/pysurfex/bin/gridpp", line 17, in <module>
    surfex.run_gridpp(**kwargs)
  File "/perm/sp3c/hm_lib/devcy46h1_tDl/lib/util/pysurfex/surfex/cli.py", line 1283, in run_gridpp
    field = surfex.horizontal_oi(geo, background, observations, gelevs, hlength=hlength,
  _**File "/perm/sp3c/hm_lib/devcy46h1_tDl/lib/util/pysurfex/surfex/assim.py", line 82, in horizontal_oi
    if np.isnan(pbackground[point]):**_
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

where the code in assim.py:

[81]        for point in enumerate(lons):
[82]            if np.isnan(pbackground[point]):
                logging.info("Undefined background in lon=%s lat=%s value=%s",
                             lons[point], lats[point], values[point])

The error is produced because "point" is tuple (index, value). I just changed it this way:
[81]        for point,value in enumerate(lons):
[82]            if np.isnan(pbackground[point]):

 and the error disappeared...

**Comment by trygveasp** [comment]
Should be solved by:
https://github.com/metno/pysurfex/commit/17961e10600cbb8ed33e1002f37e3116e7d64ac7
